# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane


  lane :release do
    get_push_certificate
    capture_screenshots                  # generate new screenshots for the App Store
    sync_code_signing(type: "appstore")  # see code signing guide for more information
    build_app(scheme: "pregnancyPhoto")
    upload_to_app_store
  end
